### ISSUE TITLE
dashboard URI deprecated in Grafana 5.0+ api

### ISSUE THREAD

**Issue by thewaywest** [SoftwareMansion/grafana-backup-s3#1]
[
  {
    "id": 163,
    "uid": "000000163",
    "title": "Folder",
    "url": "/dashboards/f/000000163/folder",
    "type": "dash-folder",
    "tags": [],
    "isStarred": false,
    "uri":"db/folder" **// deprecated in Grafana v5.0**
  },
  {
    "id":1,
    "uid": "cIBgcSjkk",
    "title":"Production Overview",
    "url": "/d/cIBgcSjkk/production-overview",
    "type":"dash-db",
    "tags":[prod],
    "isStarred":true,
    "uri":"db/production-overview" **// deprecated in Grafana v5.0**
  }
]

**Comment by mkaput** [comment]
Hello! This repository is basically unmaintained. Feel free to fork it and fix the issues there.
